CompanyWebPage.Web/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace CompanyWebPage.Web.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult About()
        {
            return View();
        }
    }
}

CompanyWebPage.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace CompanyWebPage.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View();
        }
    }
}

CompanyWebPage.Web/Controllers/NewsletterController.cs
using Microsoft.AspNetCore.Mvc;

namespace CompanyWebPage.Web.Controllers
{
    public class NewsletterController : Controller
    {
        public IActionResult Subscribe()
        {
            return View(new ViewModel.NewsletterSubscribeViewModel());
        }

        [HttpPost]
        public IActionResult Subscribe(ViewModel.NewsletterSubscribeViewModel model)
        {
            if (ModelState.IsValid)
            {
                // save data (todo: in the future)

                // redirect to /Home/Index
                return RedirectToAction(nameof(HomeController.Index), "Home");                
            }
            else
                return View(model);
        }
    }
}

CompanyWebPage.Web/Views/About/About.cshtml
<h1 class="display-4">Welcome</h1>

CompanyWebPage.Web/Views/About/About.es.cshtml
<h1 class="display-4">¡Bienvenido!</h1>

CompanyWebPage.Web/Views/Home/Index.cshtml
<div class="text-center">
    <h1 class="display-4">Welcome</h1>
</div>
<div class="text-center">
    <a class="nav-link text-dark" asp-area="" asp-controller="Newsletter" asp-action="Subscribe" id="NewsletterLink">Subscribe to newsletter</a>
</div>

CompanyWebPage.Web/Views/Home/Index.es.cshtml
<div class="text-center">
    <h1 class="display-4">¡Bienvenido!</h1>
</div>
<div class="text-center">
    <img src="~/img/Spain.png"/>
</div>
<div class="text-center">
    <a class="nav-link text-dark" asp-area="" asp-controller="Newsletter" asp-action="Subscribe" id="NewsletterLink">Suscríbase al boletín</a>
</div>

CompanyWebPage.Web/Views/Newsletter/Subscribe.cshtml
@model CompanyWebPage.ViewModel.NewsletterSubscribeViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="offset-3 col-6">
    <h1>Subscribe to newsletter</h1>
</div>
@if (ViewData.ModelState.Any(x => x.Value.Errors.Any()))
{
    <div class="offset-3 col-6 alert alert-danger">
        Errors:<br/>
        @Html.ValidationSummary()
    </div>
}
<div class="offset-3 col-6">
    <form method="POST">
        <div class="form-group">
            @Html.LabelFor(model => model.Age)
            <input type="number" id="Age" name="Age" value="@Model.Age" class="form-control" />
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName)
            <input type="text" id="FirstName" name="FirstName" value="@Model.FirstName" class="form-control" />
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.EmailAddress)
            <input type="email" id="EmailAddress" name="EmailAddress" value="@Model.EmailAddress" class="form-control" />
        </div>
        <div class="form-group">
            <input type="submit" value="Subscribe" />
        </div>
    </form>
</div>

CompanyWebPage.Web/Views/Newsletter/Subscribe.es.cshtml
@model CompanyWebPage.ViewModel.NewsletterSubscribeViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="offset-3 col-6">
    <h1>Suscríbase al boletín <img src="~/img/Spain.png" class="newsletter-flag" /></h1>
</div>
@if (ViewData.ModelState.Any(x => x.Value.Errors.Any()))
{
<div class="offset-3 col-6 alert alert-danger">
    Errores:<br />
    @Html.ValidationSummary()
</div>
}
<div class="offset-3 col-6">
    <form method="POST">
        <div class="form-group">
            @Html.LabelFor(model => model.Age)
            <input type="number" id="Age" name="Age" value="@Model.Age" class="form-control" />
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName)
            <input type="text" id="FirstName" name="FirstName" value="@Model.FirstName" class="form-control" />
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.EmailAddress)
            <input type="email" id="EmailAddress" name="EmailAddress" value="@Model.EmailAddress" class="form-control" />
        </div>
        <div class="form-group">
            <input type="submit" value="Suscríbase" />
        </div>
    </form>
</div>

CompanyWebPage.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>The Company Web Page</title>
    <link rel="stylesheet" href="~/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="container">
        @RenderBody()
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - The Company Web Page
        </div>
    </footer>
</body>
</html>